##服务器端口号
server:
  port: 4001

spring:
  application:
    name: consumer
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
#      connectString: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      discovery:
        register: true
      enabled: true
      properties:
        authProvider:1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        requireClientAuthScheme: sasl
        jaasLoginRenew: 3600000

#  kafka:
#    bootstrap-servers:
#      127.0.0.1:9094
#    producer:
#      # 重试次数
#      retries: 3
#      # 批量发送的消息数量
#      batch-size: 1000
#      # 32MB的批处理缓冲区
#      buffer-memory: 33554432
#    consumer:
#      # 默认消费者组
#      group-id: comsumer-test
#      # 最早未被消费的offset
#      auto-offset-reset: earliest
#      # 批量一次最大拉取数据量
#      max-poll-records: 4000
#      # 是否自动提交
#      enable-auto-commit: true
#      # 自动提交时间间隔，单位ms
#      auto-commit-interval: 1000