server:
  port: 4000

spring:
  application:
    name: provider
  cloud:
    zookeeper:
      connect-string: 47.96.65.118:2181,47.96.65.118:2182,47.96.65.118:2183
#      connect-string: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      enabled: true
      properties:
        authProvider:1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        requireClientAuthScheme: sasl
        jaasLoginRenew: 3600000

  kafka:
#    bootstrap-servers: 127.0.0.1:9094,127.0.0.1:9097,127.0.0.1:9100
    bootstrap-servers: 47.96.65.118:9094,47.96.65.118:9097,47.96.65.118:9100
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: SCRAM-SHA-256
    producer:
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 1000
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 默认消费者组
      group-id: test
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 4000
      # 是否自动提交
      enable-auto-commit: true
      # 自动提交时间间隔，单位ms
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.qq.com
    port: 587
    username: 525599675@qq.com
    password: vigclwxphjfcbigf
    properties:
      mail:
        smtp:
          from: 525599675@qq.com

properties:
  connectString: 47.96.65.118:2181,47.96.65.118:2182,47.96.65.118:2183
#  connectString: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
#  connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
#  connectString: 127.0.0.1:2181
  sessionTimeout: 5000
  connectionTimeout: 5000
  registrationPath: /services
  to: 525599675@qq.com
  username: user
  password: password