server:
  port: 8888

spring:
  application:
    name: provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      enabled: true
      properties:
        authProvider.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        requireClientAuthScheme: sasl
        jaasLoginRenew: 3600000
        authProvider.1.class: org.apache.zookeeper.server.auth.DigestAuthenticationProvider
        authProvider.1.digest.user: user:password

properties:
  #  connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  connectString: 127.0.0.1:2181
  sessionTimeout: 5000
  connectionTimeout: 5000
  registrationPath: /services2
  to: 525599675@qq.com
  username: user
  password: password