version: '3.0'

networks:
  zk-kafka:

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zoo
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - zk-kafka
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
      - '9094:9094'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # 开发环境使用明文
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 监听器列表
      # PLAINTEXT 监听器在所有可用网络接口上监听端口 9092，用于处理普通的明文通信。
      # CONTROLLER 监听器在所有可用网络接口上监听端口 9093，用于控制器(自动，负责协调集群)之间的通信。
      # EXTERNAL 监听器在所有可用网络接口上监听端口 9094，用于与外部客户端进行通
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      # 广告监听器列表
      # 需要与监听器配置相匹配
      # PLAINTEXT 广告监听器的地址是 kafka:9092，表示内部客户端在连接 Kafka 时应该使用此地址进行通信。
      # EXTERNAL 广告监听器的地址是 localhost:9094，表示外部客户端在连接 Kafka 时应该使用此地址进行通信。
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      # 监听器使用的协议 PLAINTEXT 表示明文
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - zk-kafka

  kafka-manager:
    image: kafkamanager/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zoo:2181
    networks:
      - zk-kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local